version: "3.9"
services:
    postgres:
        image: postgres:14-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=mysecretpassword
            - POSTGRES_DB=simple_bank
        ports:
            - "5432:5432"
    api:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"
        environment:
            - DB_SOURCE=postgresql://postgres:mysecretpassword@postgres:5432/postgres?sslmode=disable
        depends_on:
            - postgres
        entrypoint: ["/wait-for.sh", "postgres:5432", "--", "/start.sh"]
        command: ["/main"]
