apiVersion: v1
kind: ConfigMap
metadata:
    name: aws-auth
    namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::270658353509:user/github-ci
      username: github-ci
      groups:
        - system:masters
  mapRoles: |
    - rolearn: arn:aws:iam::270658353509:role/github-ci
      username: github-ci
      groups:
        - system:masters