apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaosrealm-deployment
  labels:
    app: chaosrealm-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chaosrealm-api
  template:
    metadata:
      labels:
        app: chaosrealm-api
    spec:
      containers:
      - name: nginx
        image: 270658353509.dkr.ecr.us-east-2.amazonaws.com/chaosrealm:latest
<<<<<<< HEAD
<<<<<<< HEAD
        imagePullPolicy: Always
=======
>>>>>>> 485afdc (update CI to deploy to aws eks)
=======
        imagePullPolicy: Always
>>>>>>> d603782 (add image pull policy)
        ports:
        - containerPort: 8080
