name: deploy to docker hub

on:
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
    deploy:
        name: Build image
        runs-on: ubuntu-latest

        steps:
        
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Login to GitHub Package Registry
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        - name: Build and push image
          run: |
            docker build -t cocopanda/chaosrealm:latest .
            docker push cocopanda/chaosrealm:latest